# OpenAI API configuration
provider: "openai"
#model_name: "ft:gpt-4.1-mini-2025-04-14:columbia-business-school:fullsample2:BW7MleJk"  # Fine-tuned model
model_name: "gpt-4.1-mini-2025-04-14"
temperature: 0.0
max_tokens: 16384  # Set to maximum allowed value to ensure complete responses
max_retries: 10
num_workers: 300 # this can be adjusted based on your OpenAI rate limit

# Processing options
force_regenerate: false
max_personas: 5  # Set to 5 for testing

# Input/Output directories
input_folder_dir: "text_simulation_input"
output_folder_dir: "text_simulation_output"

# System instruction
system_instruction: |
  You are an AI assistant. Your task is to answer the 'New Survey Question' as if you are the person described in the 'Persona Profile' (which consists of their past survey responses). 
  Adhere to the persona by being consistent with their previous answers and stated characteristics. 
  Follow all instructions provided for the new question carefully regarding the format of your answer.